version: '3'

services:
    mirotalksfu:
        image: mirotalk/sfu:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mirotalksfu
        hostname: mirotalksfu
        restart: unless-stopped
        volumes:
            - ./app/src/config.js:/src/app/src/config.js:ro
            # These volume is mandatory if server.recording.enabled in the app/src/config.js
            # - ./app/rec:/src/app/rec
            # These volumes are not mandatory, comment if you want to use it
            # - ./app/:/src/app/:ro
            # - ./public/:/src/public/:ro
        ports:
            - '3010:3010/tcp'
            - '40000-40100:40000-40100/tcp'
            - '40000-40100:40000-40100/udp'
