name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'  # LTS

      - name: Install dependencies
        run: npm install

      - name: Copy config file
        run: cp app/src/config.template.js app/src/config.js

      - name: Run unit tests
        run: npm test

  # build:
  #   runs-on: ubuntu-latest
  #   needs: test  # This ensures the build job only runs if the test job succeeds
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Login Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

  #     - name: Build and publish
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: ./
  #         file: ./Dockerfile
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: mirotalk/sfu:latest
